export const categories = [
    { id: 1, name: "슈퍼히어로"} ,
    { id: 2, name: "게임"} ,
    { id: 3, name: "영화"} ,
    { id: 4, name: "연예인"} ,
    { id: 5, name: "자동차"} ,
    { id: 6, name: "자연"} ,
    { id: 7, name: "TV 프로그램"} ,
    { id: 8, name: "여행"} ,
    { id: 9, name: "애니메이션"} ,
    { id: 10, name: "음악"} ,
    { id: 11, name: "사진"} ,
    { id: 12, name: "컴퓨터"} ,
    { id: 13, name: "동물"} ,
    { id: 14, name: "스포츠"} ,
    { id: 15, name: "만화"} ,
    { id: 16, name: "축하"} ,
    { id: 17, name: "그래픽"} ,
    { id: 18, name: "영감"} ,
    { id: 19, name: "라이프스타일"} ,
    { id: 20, name: "음식"} ,
]